/* Populated by react-webpack-redux:action */
export const AUTHORIZATION = 'AUTHORIZATION';
export const SET_CURRENT_BOARD = 'SET_CURRENT_BOARD';
export const SET_CURRENT_LIST = 'SET_CURRENT_LIST';
export const UPDATE_LIST = 'UPDATE_LIST';
export const UPDATE_DONE_LIST = 'UPDATE_DONE_LIST';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER = 'SET_USER';
export const LOGOUT = 'LOGOUT';
export const SHOW_SETTINGS_PAGE = 'SHOW_SETTINGS_PAGE';
export const HIDE_SETTINGS_PAGE = 'HIDE_SETTINGS_PAGE';
export const SET_AVAILABLE_BOARDS = 'SET_AVAILABLE_BOARDS';
export const SET_ACTIVE_BOARD_ID = 'SET_ACTIVE_BOARD_ID';
